services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: db_app

  app:
    image: alpine
    command: sleep infinity
    env_file: 
      - ./app.env

  cache:
    image: redis:alpine
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-defaultpass}


    

