services:
  app:
    build: .
    container_name: notes-app
    ports:
      - "${SERVER_PORT}:8080"
    
    environment:
      APP_NAME: ${APP_NAME}
      APP_VERSION: ${APP_VERSION}
      APP_ENV: ${APP_ENV}
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      UPLOAD_PATH: /app/uploads
      MAX_FILE_SIZE: ${MAX_FILE_SIZE}
      LOG_LEVEL: ${LOG_LEVEL}
      SHOW_SQL: ${SHOW_SQL}
    
    volumes:
      - notes_uploads:/app/uploads
    
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: notes-db
    
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    
    volumes:
      - notes_pg_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d:ro

volumes:
  notes_uploads:
  notes_pg_data:


# docker compose up -d --build
# docker compose ps

# curl http://localhost:8080/api/info/env

# curl -X POST http://localhost:8080/api/notes \
#   -H "Content-Type: application/json" \
#   -d '{"title":"Test persistance","content":"Cette note doit survivre"}'



# curl http://localhost:8080/api/notes

# docker compose down -v

# docker compose up -d

# curl http://localhost:8080/api/notes


# # Modifier APP_NAME dans .env
# # APP_NAME=Mon Application Modifiée

# # Recréer le conteneur app
# docker compose up -d --force-recreate app

# # Vérifier le changement
# curl http://localhost:8080/api/info/app
# # Le nom doit avoir changé